/*
 * This source file was generated by the Gradle 'init' task
 */
package com.i0nut02.lsm;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    @Test void appHasAGreeting() {
        System.out.println("testing");
    }
}
